import { relations, source } from '../../source-factory';

const tableData = { headers: ['시기', '남중 고도', '낮 길이'], rows: [['3월', '56도', '12시간 20분'], ['6월', '74도', '14시간 42분'], ['9월', '48도', '11시간 35분']] };
const common = { caseId: 'seasonal-sun', scopeSummary: '가상 관측 지점 한 곳', methodSummary: '같은 방법으로 남중 고도와 낮 길이를 기록함' };
export const scienceSources = [
  source({ ...common, id: 'sun-table', originId: 'origin-sun-table', publisherLabel: '가상 하늘관측소', sourceType: '합성 관측표', publishedAt: '2026-10-01', periodLabel: '2026년 3·6·9월', excerpt: '3월·6월·9월 값은 있지만 12월 값은 아직 없습니다.', assessments: relations({ subject: 'supports', relation: 'supports', measure: 'limits' }), tableData }),
  source({ ...common, id: 'sun-infographic', originId: 'origin-sun-table', derivedFromId: 'sun-table', publisherLabel: '가상 과학소식', sourceType: '관측표 재게시 그림', publishedAt: '2026-10-02', periodLabel: '2026년 3·6·9월', excerpt: '같은 관측표를 그림으로 옮긴 자료라 독립된 두 번째 관측은 아닙니다.', assessments: relations({ subject: 'supports', relation: 'supports', measure: 'limits' }) }),
  source({ ...common, id: 'sun-photo', originId: 'origin-sun-photo', publisherLabel: '가상 관찰 모임', sourceType: '한낮 사진 한 장', publishedAt: '2026-06-15', periodLabel: '2026년 6월 하루', methodSummary: '한 시각의 사진을 촬영함', scopeSummary: '하루 한 장', excerpt: '사진 한 장만으로 계절 전체의 낮 길이나 12월 수치를 알 수 없습니다.', assessments: relations({ subject: 'limits', relation: 'irrelevant', measure: 'irrelevant' }) }),
  source({ ...common, id: 'sun-other', originId: 'origin-other-place', publisherLabel: '가상 먼지역 관측소', sourceType: '지역이 다른 메모', publishedAt: null, periodLabel: '날짜 표시 없음', methodSummary: '방법 표시 없음', scopeSummary: '다른 지역', excerpt: '지역과 날짜가 달라 현재 가상 관측소의 주장에 직접 적용하기 어렵습니다.', assessments: relations({ subject: 'limits', relation: 'irrelevant', measure: 'irrelevant' }) }),
  source({ ...common, id: 'sun-december', originId: 'origin-sun-december', publisherLabel: '가상 하늘관측소', sourceType: '12월 후속 관측표', publishedAt: '2026-12-22', periodLabel: '2026년 12월', excerpt: '남중 고도 29도, 낮 길이 9시간 38분으로 같은 방법의 후속 관측입니다.', assessments: relations({ subject: 'supports', relation: 'supports', measure: 'contradicts' }), tableData: { headers: ['시기', '남중 고도', '낮 길이'], rows: [['12월', '29도', '9시간 38분']] } }),
];
